language: c
compiler: gcc
sudo: false
os:
  linux

addons:
  apt:
    packages: &1
      - lcov
script:
  - make test
  - ./test
  - gcov fizzbuzz.c

after_success:
  - bash <(curl -s https://codecov.io/bash)