language: c
compiler: gcc
sudo: false
os:
  linux
before_install:
  - sudo pip install codecov
addons:
  apt:
    packages: &1
      - gcov
script:
  make test
  ./test
  gcov fizzbuzz.c

after_success:
  - bash <(curl -s https://codecov.io/bash)